// frontend/src/components/Register.tsx
import { memo, type FormEvent } from 'react';
import { THEMES, type Theme } from '../theme';
import { Masthead } from './Masthead';

interface RegisterProps {
  readonly name: string;
  readonly observer: boolean;
  readonly submitted: boolean;
  readonly theme: Theme;
  readonly error?: string;
  readonly onNameChange: (name: string) => void;
  readonly onObserverChange: (observer: boolean) => void;
  readonly onDismissError: () => void;
  readonly onRegister: () => void;
}

export const Register = memo(function Register({
  name,
  observer,
  submitted,
  theme,
  error,
  onNameChange,
  onObserverChange,
  onDismissError,
  onRegister,
}: RegisterProps) {
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onRegister();
  };

  return (
    <main>
      <Masthead full theme={theme} />
      <section aria-label="Register" className="register-panel">
        {error ? (
          <div className="error" role="alert">
            <strong>Failed!</strong> {error}
            <button aria-label="Close" className="close" onClick={onDismissError} type="button">
              <span aria-hidden="true">×</span>
            </button>
          </div>
        ) : null}
        <form noValidate onSubmit={submit}>
          <label className="field-label" htmlFor="name">Name</label>
          <input
            autoComplete="off"
            className="text-input"
            id="name"
            maxLength={24}
            name="name"
            onChange={(event) => onNameChange(event.target.value)}
            placeholder={THEMES[theme].placeholder}
            type="text"
            value={name}
          />
          <label className="check" htmlFor="observer">
            <input
              aria-label="Observer mode"
              checked={observer}
              id="observer"
              onChange={(event) => onObserverChange(event.target.checked)}
              type="checkbox"
            />
            Observer mode <span aria-hidden="true" className="hint">— watch, don't vote</span>
          </label>
          <button className="btn primary" disabled={name.length < 3 || submitted} type="submit">
            {THEMES[theme].join}
          </button>
        </form>
      </section>
    </main>
  );
});

// frontend/src/app/register/register.component.ts
import { Component, EventEmitter, Input, Output, OnDestroy } from '@angular/core';
import { Subject } from 'rxjs';
import { WebSocketService } from '@app/services/web-socket.service';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html'
})
export class RegisterComponent implements OnDestroy {

  error = '';
  submitted = false;

  constructor(private webSocketService: WebSocketService) {
  }

  @Input() name!: string;
  @Output() nameChange = new EventEmitter<string>();

  @Output() registeredChange = new EventEmitter<boolean>();
  private destroyed$ = new Subject();

  nameChanged(newName: string): void {
    this.name = newName;
    this.nameChange.emit(newName);
  }

  register(): void {
    // Do something
    this.error = '';
    this.webSocketService.register(this.name).pipe(
      takeUntil(this.destroyed$)
    ).subscribe(result => {
      if (!result) {
        this.error = this.webSocketService.lastError ?? '';
      }
      this.registeredChange.emit(result);
    });
  }

  ngOnDestroy(): void {
    this.destroyed$.next();
  }

}

<div class="container" style="margin-top:10px;">
  <form>
    <div *ngIf="error" class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>Failed!</strong> {{error}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" name="name" class="form-control" autocomplete="off" id="name" [ngModel]="name" (ngModelChange)="nameChanged($event)">
<!--      <div class="form-check">-->
<!--        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">-->
<!--        <label class="form-check-label" for="flexCheckDefault">-->
<!--          Observer mode-->
<!--        </label>-->
<!--      </div>-->
    </div>
    <button type="submit" class="btn btn-primary" [disabled]="name.length < 3 || submitted"
            (click)="register()">Submit</button>
  </form>
</div>
